inherit_gem:
  rubocop-discourse: default.yml

# Still work to do in ensuring we don't link old files
Discourse/NoAddReferenceOrAliasesActiveRecordMigration:
  Enabled: false

Discourse/NoResetColumnInformationInMigrations:
  Enabled: true

# TODO: Still need to fix all the existing tests but we shouldn't block future upgrades
Discourse/NoMockingJobs:
  Enabled: false
