language: ruby

env:
  global:
    - DISCOURSE_HOSTNAME=www.example.com
    - RUBY_GC_MALLOC_LIMIT=50000000
  matrix:
    - "RAILS_MASTER=1"
    - "RAILS_MASTER=0"

matrix:
  allow_failures:
    - rvm: 2.0.0
      env: "RAILS_MASTER=1"
    - rvm: 2.1
      env: "RAILS_MASTER=1"
  fast_finish: true

rvm:
  - 2.0.0
  - 2.1

services:
  - redis-server

sudo: false

cache: bundler

before_install:
  - npm i -g jshint
  - jshint .

before_script:
  - psql -c 'create database discourse_test;' -U postgres
  - bundle exec rake db:migrate

bundler_args: --without development --deployment --retry=3 --jobs=3

script: 'bundle exec rspec && bundle exec rake plugin:spec && bundle exec rake qunit:test'
