language: ruby
rvm:
  - 1.9.3
before_script:
  - psql -c 'create database discourse_test;' -U postgres
  - rake db:migrate
script: 'rake spec && bundle exec guard-jasmine --server-timeout=60'
services:
  - redis-server