language: ruby

rvm:
  - 2.0.0
  - 2.1

services:
  - redis-server

sudo: false

cache: bundler

env:
  global:
    - DISCOURSE_HOSTNAME=www.example.com
    - RUBY_GC_MALLOC_LIMIT=50000000

before_install:
  - npm i -g jshint
  - jshint .

before_script:
  - psql -c 'create database discourse_test;' -U postgres
  - bundle exec rake db:migrate

bundler_args: --without development --deployment

script: 'bundle exec rspec && bundle exec rake plugin:spec && bundle exec rake qunit:test'
