language: ruby
rvm:
  - 2.0.0
before_script:
  - psql -c 'create database discourse_test;' -U postgres
  - rake db:migrate
  - export RUBY_GC_MALLOC_LIMIT=50000000
bundler_args: --without development
script: 'bundle exec rspec && bundle exec rake qunit:test'
services:
  - redis-server
