data_dir: /shared/import/data

# mbox files
split_regex: "^From .+@.+"
#split_regex: "^From .+@example.com.+"

# individual emails
#split_regex: ""

# Listserv files
#split_regex: "^========================================================================="

default_trust_level: 1
prefer_html: true
staged: true
index_only: false

group_messages_by_subject: false

# Remove prefixes like [FOO] or (BAR) from topic titles and replace them with tags.
# You can map one or more case-insensitive prefixes to the same tag in Discourse.
# "Tag name in Discourse": "foo"
# "Tag name in Discourse": ["foo", "bar"]
# You can use an empty tag name to remove prefixes without creating a tag in Discourse.
tags:
#  "off-topic": "ot"
#  announcement: ["ann", "announce", "announcement"]
#  "": ["foo", "bar"]

# These prefixes will be removed from the beginning of topic titles. You can use regular expessions.
# Prefixes are case-insensitive. You can add additional prefixes (e.g. localized prefixes from
# https://en.wikipedia.org/wiki/List_of_email_subject_abbreviations#Abbreviations_in_other_languages).
remove_subject_prefixes:
  - "Re: "
  - "Fwd?: "