# PostgreSQL mailing lists
#data_dir: /shared/import/data
#split_regex: "^From .*@postgresql.org.*"

# ruby-talk mailing list
data_dir: /shared/import/data
split_regex: ""

default_trust_level: 1
prefer_html: false
