name: (experimental) Ember CLI tests (plugins)

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    container: discourse/discourse_test:release
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Git
        run: |
          git config --global user.email "ci@ci.invalid"
          git config --global user.name "Discourse CI"

      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Official Plugins Install
        run: |
          bundle config --local path vendor/bundle
          bundle config --local deployment true
          bundle config --local without development
          bundle install --jobs 4
          bundle clean
          bundle exec rake plugin:install_all_official

      - name: QUnit
        working-directory: ./app/assets/javascripts/discourse
        run: QUNIT_EMBER_CLI=1 sudo -E -u discourse -H rake plugin:qunit
        timeout-minutes: 60
